USE [master]
GO

/****** Object:  Database [final_capstone]    Script Date: 4/13/2023 5:28:53 PM ******/
CREATE DATABASE [final_capstone]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'final_capstone', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\final_capstone.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'final_capstone_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\final_capstone_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [final_capstone].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [final_capstone] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [final_capstone] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [final_capstone] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [final_capstone] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [final_capstone] SET ARITHABORT OFF 
GO

ALTER DATABASE [final_capstone] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [final_capstone] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [final_capstone] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [final_capstone] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [final_capstone] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [final_capstone] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [final_capstone] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [final_capstone] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [final_capstone] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [final_capstone] SET  ENABLE_BROKER 
GO

ALTER DATABASE [final_capstone] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [final_capstone] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [final_capstone] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [final_capstone] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [final_capstone] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [final_capstone] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [final_capstone] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [final_capstone] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [final_capstone] SET  MULTI_USER 
GO

ALTER DATABASE [final_capstone] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [final_capstone] SET DB_CHAINING OFF 
GO

ALTER DATABASE [final_capstone] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [final_capstone] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [final_capstone] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [final_capstone] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [final_capstone] SET QUERY_STORE = OFF
GO

ALTER DATABASE [final_capstone] SET  READ_WRITE 
GO

